project:
  type: default
  output-dir: .

format:
  revealjs:
    theme: bauhaus-tech.scss
    mermaid:
      theme: neutral
    mermaid-format: png
    slide-number: true
    code-line-numbers: false
    highlight-style: github
    transition: fade
    width: 1280
    height: 720
    center: true
    hash-type: number
    navigation-mode: linear
    controls: true
    progress: true
    footer: "RAIner"
